from . import measurement
from . import spindle_type
from . import spindle_rpm
from . import spindle_motor_power
from . import machine_structure
from . import prefered_operation
from . import product_template
from . import product_product
from . import other_specification
from . import product_created_spindle_report
from . import crm_lead
